server:
  port: 9002

eureka:
  instance:
    hostname: UserService
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true

spring:
  application:
    name: UserService